name: CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Android SDK
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          yes | sdkmanager --licenses

          sdkmanager \
            "platform-tools" \
            "emulator" \
            "platforms;android-30" \
            "build-tools;36.0.0" \
            "system-images;android-30;google_apis;x86_64"

      - name: Create AVD
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          echo "no" | avdmanager create avd \
            -n test \
            -k "system-images;android-30;google_apis;x86_64" \
            -d pixel_5

          echo "hw.cpu.ncore=2" >> ~/.android/avd/test.avd/config.ini
          echo "hw.ramSize=2048" >> ~/.android/avd/test.avd/config.ini

      - name: Start Emulator
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          nohup $ANDROID_HOME/emulator/emulator \
            @test \
            -no-window \
            -gpu swiftshader_indirect \
            -noaudio \
            -no-boot-anim \
            -no-snapshot \
            > emulator.log 2>&1 &

      - name: Wait for Emulator
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
        run: |
          adb wait-for-device

          until adb shell getprop sys.boot_completed | grep -q "1"
          do
            sleep 2
          done

          adb shell input keyevent 82

          adb devices
          adb shell getprop ro.build.version.release
          adb shell getprop ro.product.cpu.abi
          adb shell wm size

      - name: Emulator Running Check
        run: |
          ps -ef | grep emulator || true
          adb devices
          
